# Generated by Django 2.2.2 on 2019-06-12 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='descrption',
            new_name='description',
        ),
    ]
